apiVersion: v1
kind: ServiceAccount
metadata:
  name: provisioner-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provisioner-operator
rules:
- apiGroups: ["kubevirt.io"]
  resources: ["virtualmachineinstances"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: ["kubevirt.io"]
  resources: ["initdatas"]
  verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provisioner-operator
subjects:
- kind: ServiceAccount
  name: provisioner-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: provisioner-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: provisioner-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provisioner-operator
  template:
    metadata:
      labels:
        app: provisioner-operator
    spec:
      serviceAccountName: provisioner-operator
      containers:
      - name: operator
        image: quay.io/mvaralar/provisioner-operator:latest
        imagePullPolicy: Always
        env:
        - name: KBS_URL
          value: "http://xx.xx.xx.xx:8080"
        - name: WATCH_NAMESPACE
          value: "default"
        - name: RUST_LOG
          value: "info"
